# Generated by Django 4.2.5 on 2023-09-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tel',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.CharField(max_length=200),
        ),
    ]
